# Generated by Django 5.1 on 2024-09-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='participant_id',
            field=models.CharField(max_length=255),
        ),
    ]
