# Generated by Django 4.2.15 on 2025-10-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_sessions', '0002_alter_chatsession_participant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
