version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 OpenAichat.wsgi:application
    volumes:
      - .:/app
    expose:
      - "8000"
    environment:
      DJANGO_SETTINGS_MODULE: OpenAichat.settings
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"  # Ajout du port 443 pour HTTPS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl  # Montez le dossier SSL contenant les certificats
      - ./staticfiles:/app/staticfiles
    depends_on:
      - web
