# Generated by Django 5.1 on 2024-09-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0001_initial'),
        ('chat_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sent_to_openai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_messages', to='chat_sessions.chatsession'),
        ),
    ]
