# Generated by Django 5.1 on 2024-09-01 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_messages', '0002_message_is_sent_to_openai_message_response_and_more'),
        ('chat_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='chat_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_sessions.chatsession'),
        ),
    ]
